# Base Image
FROM node:lts

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files into the Docker image
COPY . .

# Expose port for the development server
EXPOSE 3000

# Command to run when starting the container
CMD ["npm", "run", "dev"]
